[package]
name = "launcher-install"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
reqwest = { version = "0.12" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
sha1 = "0.10"
zip = "2"
launcher-core = { path = "../launcher-core" }
